
export const mockTags = {
  Subject: [
    {
      id: 'subject-1',
      text: 'Humans',
      zone: 'Subject',
      selected: false,
      hidden: false,
      x: null,
      y: null,
      fx: null,
      fy: null,
      parentId: null,
      vy: null,
      vx: null,
      children: [
        {
          id: 'subject-1-1',
          text: 'Adult Male',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-1',
          children: []
        },
        {
          id: 'subject-1-2',
          text: 'Adult Female',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-1',
          children: []
        },
        {
          id: 'subject-1-3',
          text: 'Child',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-1',
          children: []
        },
        {
          id: 'subject-1-4',
          text: 'Elderly',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-1',
          children: []
        },
        {
          id: 'subject-1-5',
          text: 'Group of People',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-1',
          children: []
        },
        {
          id: 'subject-1-6',
          text: 'Portrait',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-1',
          children: []
        },
        {
          id: 'subject-1-7',
          text: 'Silhouette',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-1',
          children: []
        }
      ]
    },
    {
      id: 'subject-2',
      text: 'Animals',
      zone: 'Subject',
      selected: false,
      hidden: false,
      x: null,
      y: null,
      fx: null,
      fy: null,
      parentId: null,
      children: [
        {
          id: 'subject-2-1',
          text: 'Mammals',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-2',
          children: []
        },
        {
          id: 'subject-2-2',
          text: 'Birds',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-2',
          children: []
        },
        {
          id: 'subject-2-3',
          text: 'Reptiles',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-2',
          children: []
        },
        {
          id: 'subject-2-4',
          text: 'Fish',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-2',
          children: []
        },
        {
          id: 'subject-2-5',
          text: 'Insects',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-2',
          children: []
        },
        {
          id: 'subject-2-6',
          text: 'Amphibians',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-2',
          children: []
        },
        {
          id: 'subject-2-7',
          text: 'Prehistoric Animals',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-2',
          children: []
        },
        {
          id: 'subject-2-8',
          text: 'Sea Creatures',
          zone: 'Subject',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: 'subject-2',
          children: []
        }
      ]
      },
      {
        id: 'subject-3',
        text: 'Mythical Creatures',
        zone: 'Subject',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'subject-3-1',
            text: 'Dragons',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-3',
            children: []
          },
          {
            id: 'subject-3-2',
            text: 'Unicorns',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-3',
            children: []
          },
          {
            id: 'subject-3-3',
            text: 'Phoenix',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-3',
            children: []
          },
          {
            id: 'subject-3-4',
            text: 'Griffins',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-3',
            children: []
          },
          {
            id: 'subject-3-5',
            text: 'Mermaids',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-3',
            children: []
          },
          {
            id: 'subject-3-6',
            text: 'Centaurs',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-3',
            children: []
          },
          {
            id: 'subject-3-7',
            text: 'Giants',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-3',
            children: []
          }
        ]
      },
      {
        id: 'subject-4',
        text: 'Plants',
        zone: 'Subject',
        selected: false,
        hidden: false,
        children: [
          {
            id: 'subject-4-1',
            text: 'Trees',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-4',
            children: []
          },
          {
            id: 'subject-4-2',
            text: 'Flowers',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-4',
            children: []
          },
          {
            id: 'subject-4-3',
            text: 'Grass',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-4',
            children: []
          },
          {
            id: 'subject-4-4',
            text: 'Mushrooms',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-4',
            children: []
          },
          {
            id: 'subject-4-5',
            text: 'Vines',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-4',
            children: []
          },
          {
            id: 'subject-4-6',
            text: 'Underwater Plants',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-4',
            children: []
          },
          {
            id: 'subject-4-7',
            text: 'Carnivorous Plants',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-4',
            children: []
          }
        ]
      },
      {
        id: 'subject-5',
        text: 'Objects',
        zone: 'Subject',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'subject-5-1',
            text: 'Vehicles',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-5',
            children: []
          },
          {
            id: 'subject-5-2',
            text: 'Instruments',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-5',
            children: []
          },
          {
            id: 'subject-5-3',
            text: 'Food Items',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-5',
            children: []
          },
          {
            id: 'subject-5-4',
            text: 'Weapons',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-5',
            children: []
          },
          {
            id: 'subject-5-5',
            text: 'Clothing',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-5',
            children: []
          },
          {
            id: 'subject-5-6',
            text: 'Technology',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-5',
            children: []
          },
          {
            id: 'subject-5-7',
            text: 'Furniture',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-5',
            children: []
          },
          {
            id: 'subject-5-8',
            text: 'Art',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-5',
            children: []
          },
          {
            id: 'subject-5-9',
            text: 'Other',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-5',
            children: []
          }
        ]
      },
      {
        id: 'subject-6',
        text: 'Abstract Concepts',
        zone: 'Subject',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'subject-6-1',
            text: 'Love',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          },
          {
            id: 'subject-6-2',
            text: 'Time',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          },
          {
            id: 'subject-6-3',
            text: 'Freedom',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          },
          {
            id: 'subject-6-4',
            text: 'Emotion',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          },
          {
            id: 'subject-6-5',
            text: 'Infinity',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          },
          {
            id: 'subject-6-6',
            text: 'Harmony',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          },
          {
            id: 'subject-6-7',
            text: 'Chaos',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          },
          {
            id: 'subject-6-8',
            text: 'Knowledge',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          },
          {
            id: 'subject-6-9',
            text: 'Death',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          },
          {
            id: 'subject-6-10',
            text: 'Beauty',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          },
          {
            id: 'subject-6-11',
            text: 'Truth',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          },
          {
            id: 'subject-6-12',
            text: 'Justice',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-6',
            children: []
          }
        ]
      },
      {
        id: 'subject-7',
        text: 'Landscapes',
        zone: 'Subject',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'subject-7-1',
            text: 'Mountains',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-7',
            children: []
          },
          {
            id: 'subject-7-2',
            text: 'Forests',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-7',
            children: []
          },
          {
            id: 'subject-7-3',
            text: 'Beaches',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-7',
            children: []
          },
          {
            id: 'subject-7-4',
            text: 'Valleys',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-7',
            children: []
          },
          {
            id: 'subject-7-5',
            text: 'Islands',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-7',
            children: []
          },
          {
            id: 'subject-7-6',
            text: 'Deserts',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-7',
            children: []
          },
          {
            id: 'subject-7-7',
            text: 'Caves',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-7',
            children: []
          },
          {
            id: 'subject-7-8',
            text: 'Other',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-7',
            children: []
          }
        ]
      },
      {
        id: 'subject-8',
        text: 'Structures',
        zone: 'Subject',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'subject-8-1',
            text: 'Castles',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-8',
            children: []
          },
          {
            id: 'subject-8-2',
            text: 'Skyscrapers',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-8',
            children: []
          },
          {
            id: 'subject-8-3',
            text: 'Bridges',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-8',
            children: []
          },
          {
            id: 'subject-8-4',
            text: 'Monuments',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-8',
            children: []
          },
          {
            id: 'subject-8-5',
            text: 'Towers',
            zone: 'Subject',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'subject-8',
            children: []
          }
        ]
      }
    ],
    Attributes: [
        {
          id: 'attributes-1',
          text: 'Roles',
          zone: 'Attributes',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: null,
          children: [
            {
              id: 'attributes-1-1',
              text: 'Hero',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-1',
              children: []
            },
            {
              id: 'attributes-1-2',
              text: 'Villain',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-1',
              children: []
            },
            {
              id: 'attributes-1-3',
              text: 'Mentor',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-1',
              children: []
            },
            {
              id: 'attributes-1-4',
              text: 'Sidekick',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-1',
              children: []
            },
            {
              id: 'attributes-1-5',
              text: 'Leader',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-1',
              children: []
            },
            {
              id: 'attributes-1-6',
              text: 'Ninja',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-1',
              children: []
            }
          ]
        },
        {
          id: 'attributes-2',
          text: 'Characteristics',
          zone: 'Attributes',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: null,
          children: [
            {
              id: 'attributes-2-1',
              text: 'Brave',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-2',
              children: []
            },
            {
              id: 'attributes-2-2',
              text: 'Intelligent',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-2',
              children: []
            },
            {
              id: 'attributes-2-3',
              text: 'Cunning',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-2',
              children: []
            },
            {
              id: 'attributes-2-4',
              text: 'Stealthy',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-2',
              children: []
            },
            {
              id: 'attributes-2-5',
              text: 'Energetic',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-2',
              children: []
            },
            {
              id: 'attributes-2-6',
              text: 'Mysterious',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-2',
              children: []
            },
            {
              id: 'attributes-2-7',
              text: 'Funny',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-2',
              children: []
            },
            {
              id: 'attributes-2-8',
              text: 'Stubborn',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-2',
              children: []
            }
          ]
        },
        {
          id: 'attributes-3',
          text: 'Emotions',
          zone: 'Attributes',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: null,
          children: [
            {
              id: 'attributes-3-1',
              text: 'Happy',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-3',
              children: []
            },
            {
              id: 'attributes-3-2',
              text: 'Sad',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-3',
              children: []
            },
            {
              id: 'attributes-3-3',
              text: 'Angry',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-3',
              children: []
            },
            {
              id: 'attributes-3-4',
              text: 'Fearful',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-3',
              children: []
            },
            {
              id: 'attributes-3-5',
              text: 'Surprised',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-3',
              children: []
            },
            {
              id: 'attributes-3-6',
              text: 'Disgusted',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-3',
              children: []
            },
            {
              id: 'attributes-3-7',
              text: 'Calm',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-3',
              children: []
            },
            {
              id: 'attributes-3-8',
              text: 'Excited',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-3',
              children: []
            }
          ]
        },
        {
          id: 'attributes-4',
          text: 'Abilities',
          zone: 'Attributes',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: null,
          children: [
            {
              id: 'attributes-4-1',
              text: 'Flying',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-4',
              children: []
            },
            {
              id: 'attributes-4-2',
              text: 'Invisibility',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-4',
              children: []
            },
            {
              id: 'attributes-4-3',
              text: 'Super Strength',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-4',
              children: []
            },
            {
              id: 'attributes-4-5',
              text: 'Martial Arts',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-4',
              children: []
            },
            {
              id: 'attributes-4-6',
              text: 'Telepathy',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-4',
              children: []
            },
            {
              id: 'attributes-4-7',
              text: 'Speed',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-4',
              children: []
            },
            {
              id: 'attributes-4-8',
              text: 'Magic',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-4',
              children: []
            },
            {
              id: 'attributes-4-9',
              text: 'Telekinesis',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-4',
              children: []
            }

          ]
        },
        {
          id: 'attributes-5',
          text: 'Occupations',
          zone: 'Attributes',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: null,
          children: [
            {
              id: 'attributes-5-1',
              text: 'Doctor',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-5',
              children: []
            },
            {
              id: 'attributes-5-2',
              text: 'Engineer',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-5',
              children: []
            },
            {
              id: 'attributes-5-3',
              text: 'Artist',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-5',
              children: []
            },
            {
              id: 'attributes-5-4',
              text: 'Scientist',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-5',
              children: []
            },
            {
              id: 'attributes-5-5',
              text: 'Pirate',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-5',
              children: []
            }
          ]
        },
        {
          id: 'attributes-6',
          text: 'Personality Traits',
          zone: 'Attributes',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: null,
          children: [
            {
              id: 'attributes-6-1',
              text: 'Optimistic',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-6',
              children: []
            },
            {
              id: 'attributes-6-2',
              text: 'Pessimistic',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-6',
              children: []
            },
            {
              id: 'attributes-6-3',
              text: 'Introverted',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-6',
              children: []
            },
            {
              id: 'attributes-6-4',
              text: 'Extroverted',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-6',
              children: []
            },
            {
              id: 'attributes-6-5',
              text: 'Ambitious',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-6',
              children: []
            },
            {
              id: 'attributes-6-6',
              text: 'Stubborn',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-6',
              children: []
            }
          ]
        },
        {
          text: 'Physical Traits',
          alias: 'physical traits',
          zone: 'Attributes',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: null,
          children: [
            {
              id: 'attributes-7-1',
              text: 'Tall',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-7',
              children: []
            },
            {
              id: 'attributes-7-2',
              text: 'Short',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-7',
              children: []
            },
            {
              id: 'attributes-7-3',
              text: 'Athletic',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-7',
              children: []
            },
            {
              id: 'attributes-7-4',
              text: 'Old',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-7',
              children: []
            },
            {
              id: 'attributes-7-5',
              text: 'Young',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-7',
              children: []
            },
            {
              id: 'attributes-7-6',
              text: 'Scarred',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-7',
              children: []
            },
            {
              id: 'attributes-7-7',
              text: 'Bearded',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-7',
              children: []
            },
            {
              id: 'attributes-7-8',
              text: 'Glasses',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-7',
              children: []
            },
            {
              id: 'attributes-7-9',
              text: 'Hairless',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-7',
              children: []
            }
          ]
        },
        {
          text: 'Relationships',
          alias: 'relationships',
          zone: 'Attributes',
          selected: false,
          hidden: false,
          x: null,
          y: null,
          fx: null,
          fy: null,
          parentId: null,
          children: [
            {
              id: 'attributes-8-1',
              text: 'Friend',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-8',
              children: []
            },
            {
              id: 'attributes-8-2',
              text: 'Enemy',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-8',
              children: []
            },
            {
              id: 'attributes-8-3',
              text: 'Colleague',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-8',
              children: []
            },
            {
              id: 'attributes-8-4',
              text: 'Rival',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-8',
              children: []
            },
            {
              id: 'attributes-8-5',
              text: 'Lover',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-8',
              children: []
            },
            {
              id: 'attributes-8-6',
              text: 'Child',
              zone: 'Attributes',
              selected: false,
              hidden: false,
              x: null,
              y: null,
              fx: null,
              fy: null,
              parentId: 'attributes-8',
              children: []
            }
          ]
        }
      ],
    ActivityEvent: [
      {
        id: 'activity-1',
        text: 'Action',
        alias: 'action',
        zone: 'Activity',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'activity-1-1',
            text: 'Running',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-1',
            children: []
          },
          {
            id: 'activity-1-2',
            text: 'Jumping',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-1',
            children: []
          },
          {
            id: 'activity-1-3',
            text: 'Flying',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-1',
            children: []
          },
          {
            id: 'activity-1-4',
            text: 'Swimming',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-1',
            children: []
          },
          {
            id: 'activity-1-5',
            text: 'Racing',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-1',
            children: []
          },
          {
            id: 'activity-1-6',
            text: 'Chasing',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-1',
            children: []
          },
          {
            id: 'activity-1-7',
            text: 'Fighting',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-1',
            children: []
          },
          {
            id: 'activity-1-8',
            text: 'Dancing',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-1',
            children: []
          }

        ]
      },
      {
        text: 'Celebration',
        alias: 'celebration',
        zone: 'Activity',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'activity-2-1',
            text: 'Party',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-2',
            children: []
          },
          {
            id: 'activity-2-2',
            text: 'Festival',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-2',
            children: []
          },
          {
            id: 'activity-2-3',
            text: 'Parade',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-2',
            children: []
          },
          {
            id: 'activity-2-4',
            text: 'Wedding',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-2',
            children: []
          },
          {
            id: 'activity-2-5',
            text: 'Victory',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-2',
            children: []
          },
          {
            id: 'activity-2-6',
            text: 'Reunion',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-2',
            children: []
          },
          {
            id: 'activity-2-7',
            text: 'Graduation',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-2',
            children: []
          },
          {
            id: 'activity-2-8',
            text: 'Birthday',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-2',
            children: []
          }
        ]
      },
      {
        text: 'Exploration',
        alias: 'exploration',
        zone: 'Activity',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'activity-3-1',
            text: 'Hiking',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-3',
            children: []
          },
          {
            id: 'activity-3-2',
            text: 'Sailing',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-3',
            children: []
          },
          {
            id: 'activity-3-3',
            text: 'Space Travel',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-3',
            children: []
          },
          {
            id: 'activity-3-4',
            text: 'Deep Sea Diving',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-3',
            children: []
          },
          {
            id: 'activity-3-5',
            text: 'Time Travel',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-3',
            children: []
          },
          {
            id: 'activity-3-6',
            text: 'Discovery',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-3',
            children: []
          },
          {
            id: 'activity-3-7',
            text: 'Expedition',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-3',
            children: []
          },
          {
            id: 'activity-3-8',
            text: 'Journey',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-3',
            children: []
          }
        ]
      },
      {
        text: 'Conflict',
        alias: 'conflict',
        zone: 'Activity',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'activity-4-1',
            text: 'Battle',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-4',
            children: []
          },
          {
            id: 'activity-4-2',
            text: 'Argument',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-4',
            children: []
          },
          {
            id: 'activity-4-3',
            text: 'Survival',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-4',
            children: []
          },
          {
            id: 'activity-4-4',
            text: 'Duel',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-4',
            children: []
          },
          {
            id: 'activity-4-5',
            text: 'War',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-4',
            children: []
          },
          {
            id: 'activity-4-6',
            text: 'Competition',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-4',
            children: []
          },
          {
            id: 'activity-4-7',
            text: 'Protest',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-4',
            children: []
          },
          {
            id: 'activity-4-8',
            text: 'Struggle',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-4',
            children: []
          },
          {
            id: 'activity-4-9',
            text: 'Survival',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-4',
            children: []
          }
        ]
      },
      {
        text: 'Transformation',
        alias: 'transformation',
        zone: 'Activity',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'activity-5-1',
            text: 'Metamorphosis',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-5',
            children: []
          },
          {
            id: 'activity-5-2',
            text: 'Evolution',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-5',
            children: []
          },
          {
            id: 'activity-5-3',
            text: 'Decay',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-5',
            children: []
          },
          {
            id: 'activity-5-4',
            text: 'Aging',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-5',
            children: []
          },
          {
            id: 'activity-5-5',
            text: 'Rebirth',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-5',
            children: []
          },
          {
            id: 'activity-5-6',
            text: 'Shape-shifting',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-5',
            children: []
          },
          {
            id: 'activity-5-7',
            text: 'Growth',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-5',
            children: []
          }
        ]
      },
      {
        id: 'activity-6',
        text: 'Creation',
        alias: 'creation',
        zone: 'Activity',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'activity-6-1',
            text: 'Painting',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-6',
            children: []
          },
          {
            id: 'activity-6-2', 
            text: 'Sculpting',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-6',
            children: []
          },
          {
            id: 'activity-6-3',
            text: 'Building',
            zone: 'Activity', 
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-6',
            children: []
          },
          {
            id: 'activity-6-4',
            text: 'Writing',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-6',
            children: []
          },
          {
            id: 'activity-6-5',
            text: 'Invention',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-6',
            children: []
          },
          {
            id: 'activity-6-6',
            text: 'Programming',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-6',
            children: []
          },
          {
            id: 'activity-6-7',
            text: 'Cooking',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-6',
            children: []
          },
          {
            id: 'activity-6-8',
            text: 'Designing',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-6',
            children: []
          }
        ]
      },
      {
        id: 'activity-7',
        text: 'Destruction',
        alias: 'destruction',
        zone: 'Activity',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'activity-7-1',
            text: 'Explosion',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-7',
            children: []
          },
          {
            id: 'activity-7-2',
            text: 'Fire',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-7',
            children: []
          },
          {
            id: 'activity-7-3',
            text: 'Collapse',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-7',
            children: []
          },
          {
            id: 'activity-7-4',
            text: 'Erosion',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-7',
            children: []
          },
          {
            id: 'activity-7-5',
            text: 'Storm',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-7',
            children: []
          },
          {
            id: 'activity-7-6',
            text: 'Flood',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-7',
            children: []
          },
          {
            id: 'activity-7-7',
            text: 'Earthquake',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-7',
            children: []
          },
          {
            id: 'activity-7-8',
            text: 'Apocalypse',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-7',
            children: []
          }
        ]
      },
      {
        id: 'activity-8',
        text: 'Peaceful Moments',
        alias: 'peaceful moments',
        zone: 'Activity',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'activity-8-1',
            text: 'Sleeping',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-8',
            children: []
          },
          {
            id: 'activity-8-2',
            text: 'Meditating',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-8',
            children: []
          },
          {
            id: 'activity-8-3',
            text: 'Reading',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-8',
            children: []
          },
          {
            id: 'activity-8-4',
            text: 'Watching Sunset',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-8',
            children: []
          },
          {
            id: 'activity-8-5',
            text: 'Listening to Music',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-8',
            children: []
          },
          {
            id: 'activity-8-6',
            text: 'Gardening',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-8',
            children: []
          },
          {
            id: 'activity-8-7',
            text: 'Fishing',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-8',
            children: []
          },
          {
            id: 'activity-8-8',
            text: 'Stargazing',
            zone: 'Activity',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'activity-8',
            children: []
          }
        ]
      }
    ],

    StyleAesthetic: [
      {
        id: 'style-1',
        text: 'Realism',
        alias: 'realism',
        zone: 'Style',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'style-1-1',
            text: 'Photorealism',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-1',
            children: []
          },
          {
            id: 'style-1-2',
            text: 'Hyperrealism',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-1',
            children: []
          },
          {
            id: 'style-1-3',
            text: 'Naturalism',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-1',
            children: []
          },
          {
            id: 'style-1-4',
            text: 'Documentary Style',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-1',
            children: []
          },
          {
            id: 'style-1-5',
            text: 'Classical Realism',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-1',
            children: []
          },
          {
            id: 'style-1-6',
            text: 'Contemporary Realism',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-1',
            children: []
          },
          {
            id: 'style-1-7',
            text: 'Academic Art',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-1',
            children: []
          },
          {
            id: 'style-1-8',
            text: 'Trompe-l\'œil',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-1',
            children: []
          }
        ]
      },
      {
        id: 'style-2',
        text: 'Impressionism',
        alias: 'impressionism',
        zone: 'Style',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'style-2-1',
            text: 'Pointillism',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-2',
            children: []
          },
          {
            id: 'style-2-2',
            text: 'Plein Air',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-2',
            children: []
          },
          {
            id: 'style-2-3',
            text: 'Light Play',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-2',
            children: []
          },
          {
            id: 'style-2-4',
            text: 'Soft Brushwork',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-2',
            children: []
          },
          {
            id: 'style-2-5',
            text: 'Color Emphasis',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-2',
            children: []
          },
          {
            id: 'style-2-6',
            text: 'Atmospheric Effects',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-2',
            children: []
          },
          {
            id: 'style-2-7',
            text: 'Broken Color',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-2',
            children: []
          },
          {
            id: 'style-2-8',
            text: 'Loose Composition',
            zone: 'Style',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'style-2',
            children: []
          }
        ]
      }
    ],
  
    MoodAtmosphere: [
      {
        id: 'mood-1',
        text: 'Joyful',
        alias: 'joyful',
        zone: 'Mood',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'mood-1-1',
            text: 'Cheerful',
            zone: 'Mood',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'mood-1',
            children: []
          },
          {
            id: 'mood-1-2',
            text: 'Playful',
            zone: 'Mood',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'mood-1',
            children: []
          },
          {
            id: 'mood-1-3',
            text: 'Excited',
            zone: 'Mood',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'mood-1',
            children: []
          },
          {
            id: 'mood-1-4',
            text: 'Content',
            zone: 'Mood',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'mood-1',
            children: []
          },
          {
            id: 'mood-1-5',
            text: 'Blissful',
            zone: 'Mood',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'mood-1',
            children: []
          },
          {
            id: 'mood-1-6',
            text: 'Optimistic',
            zone: 'Mood',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'mood-1',
            children: []
          },
          {
            id: 'mood-1-7',
            text: 'Festive',
            zone: 'Mood',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'mood-1',
            children: []
          },
          {
            id: 'mood-1-8',
            text: 'Whimsical',
            zone: 'Mood',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'mood-1',
            children: []
          }
        ]
      }
    ],
  
    SettingEnvironment: [
      {
        id: 'setting-1',
        text: 'Urban',
        alias: 'urban',
        zone: 'Setting',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'setting-1-1',
            text: 'City Streets',
            zone: 'Setting',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'setting-1',
            children: []
          },
          {
            id: 'setting-1-2',
            text: 'Skyscrapers',
            zone: 'Setting',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'setting-1',
            children: []
          },
          {
            id: 'setting-1-3',
            text: 'Suburbs',
            zone: 'Setting',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'setting-1',
            children: []
          },
          {
            id: 'setting-1-4',
            text: 'Markets',
            zone: 'Setting',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'setting-1',
            children: []
          },
          {
            id: 'setting-1-5',
            text: 'Industrial Areas',
            zone: 'Setting',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'setting-1',
            children: []
          },
          {
            id: 'setting-1-6',
            text: 'Rooftops',
            zone: 'Setting',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'setting-1',
            children: []
          },
          {
            id: 'setting-1-7',
            text: 'Underground',
            zone: 'Setting',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'setting-1',
            children: []
          },
          {
            id: 'setting-1-8',
            text: 'Alleys',
            zone: 'Setting',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'setting-1',
            children: []
          }
        ]
      }
    ],
  
    CompositionLayout: [
      {
        id: 'composition-1',
        text: 'Symmetry',
        alias: 'symmetry',
        zone: 'Composition',
        selected: false,
        hidden: false,
        x: null,
        y: null,
        fx: null,
        fy: null,
        parentId: null,
        children: [
          {
            id: 'composition-1-1',
            text: 'Mirror Reflection',
            zone: 'Composition',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'composition-1',
            children: []
          },
          {
            id: 'composition-1-2',
            text: 'Radial Symmetry',
            zone: 'Composition',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'composition-1',
            children: []
          },
          {
            id: 'composition-1-3',
            text: 'Bilateral Symmetry',
            zone: 'Composition',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'composition-1',
            children: []
          },
          {
            id: 'composition-1-4',
            text: 'Kaleidoscopic',
            zone: 'Composition',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'composition-1',
            children: []
          },
          {
            id: 'composition-1-5',
            text: 'Mandala',
            zone: 'Composition',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'composition-1',
            children: []
          },
          {
            id: 'composition-1-6',
            text: 'Central Focus',
            zone: 'Composition',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'composition-1',
            children: []
          },
          {
            id: 'composition-1-7',
            text: 'Reflective Surfaces',
            zone: 'Composition',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'composition-1',
            children: []
          },
          {
            id: 'composition-1-8',
            text: 'Balanced Shapes',
            zone: 'Composition',
            selected: false,
            hidden: false,
            x: null,
            y: null,
            fx: null,
            fy: null,
            parentId: 'composition-1',
            children: []
          }
        ]
      }
    ],
  };
  